name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install Make
      run: sudo apt-get install -y build-essential
    - name: Compile
      run: make
